[package]
name = "compute-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.27.0"
wgpu = "23.0.0"
pollster = "0.4.0"
bytemuck = { version = "1.19.0", features = ["derive"] }
gltf = "1.4.1"
obj = "0.10.2"
glam = "0.29.1"
futures-intrusive = "0.5.0"
image = "0.24.4"